### PR TITLE
Add flask api and UI

### PR DESCRIPTION
**Pull request by sudodaksh**
```
cd website
export FLASK_APP=web.py
flask run
```

I'll likely add commits to the ui later tonight

pls don't merge, until I send a `done` message below

### CODE REVIEW

**Comment by sudodaksh** [comment]
@VPanjeta Done. preview the new site at: https://modiscript.netlify.com/

**Comment by VPanjeta** [comment]
Cool! looks great.
One small thing, In case of "Created by Vishal Panjeta" could you make it a something like "Created by modiscript team" or "find this project on github" which could link to github repo? It was a team project. 
You can keep the "Web UI by Daksh" link since that was completely your effort.

**Comment by sudodaksh** [comment]
Sure @VPanjeta, well I don't wanna keep my name directly on the website either (really scared of bjp xD). So if it's possible, could you please mention me in the readme or something?

Edit: I've pushed the changes to the website as well.

**Comment by VPanjeta** [comment]
Cool. Thanks for the contribution.

**Pull request merged**
