### PR TITLE
Lexer optimisation for repeated character fetch

### PR DESCRIPTION
**Pull request by narengogi**
~Inside the _analyze_lexemes() method,  characters were being searched for and compared for every if/elif condition, suppose length of the line was m, and number of if/elif conditions were n, the initial time complexity was O(mlogn), now it has been reduced to O(m+logn).~   
Optimised lexer for repeated fetch of lexemes from the line of code file and stored in local variable for removing repeated fetch of character from the string.
A simple fix. Great codebase and even better project btw!

### CODE REVIEW

**Comment by VPanjeta** [comment]
Hi @nathsin 
String indexing in all modern day programming languages runs in constant time so line[x] should be O(1). 
Anyway, your solution is still better in the case that it removes repeated operations but there are some lines where you're still using `line[offset]` inspite of having the character saved in a local variable. You can change those to your current character and rename the `curr` variable to any other meaningful name like `token`. 
Rest all looks good to me.
Thanks for the PR. Keeping it open for now in case you decide to make the changes.

**Review by VPanjeta — CHANGES_REQUESTED** [review]
`curr` to be renamed to a meaningful variable name. 
`line[offset]` to be replaced with current token variable wherever possible.

**Comment by narengogi** [comment]
Updated with suggested changes

**Review by VPanjeta — APPROVED** [review]
Looks good to me. Updated the PR info accordingly.
Thanks @nathsin.

**Pull request merged**
